apiVersion: ingress.jpmc.com/v1alpha1
kind: Route
metadata:
  name: 726de088-253c-4120-b840-72be2ecb0460
  namespace: ingress-dp
  labels:
    app.kubernetes.io/managed-by: management-api
    ingress.jpmc.com/gateway: envoy
spec:
  path: "/hello"
  hostname: "jpmm.jpm.com"
  backendUrl: "http://lambda-726de088-hello:8080"
  gatewayType: envoy
  audience: "test"
  team: "Markets"
  authnMechanism: "bearer"
  authIssuer: "Janus"
  tlsRequired: true
  targetFleet: "jpmm.jpm.com"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  healthPath: "/health"
  notes: "Deployed to fleet JPMM"
  functionCode: |
      module.exports = async (req) => ({ statusCode: 200, body: JSON.stringify({ message: "Hello from Lambda!", path: req.path }) })
  functionLanguage: javascript
status:
  phase: Pending
