apiVersion: ingress.jpmc.com/v1alpha1
kind: Fleet
metadata:
  name: fleet-jpmm
  namespace: ingress-dp
  labels:
    app.kubernetes.io/managed-by: management-api
spec:
  name: "JPMM"
  subdomain: "jpmm.jpm.com"
  gatewayType: envoy
  replicas: 2
  nodes:
    - name: "fleet-jpmm-envoy-1"
      index: 1
      datacenter: "us-east-2"
      region: "us-east-2"
      status: "running"
    - name: "fleet-jpmm-envoy-2"
      index: 2
      datacenter: "eu-west-1"
      region: "eu-west-1"
      status: "running"
