apiVersion: ingress.jpmc.com/v1alpha1
kind: Fleet
metadata:
  name: fleet-jpmm
  namespace: ingress-dp
  labels:
    app.kubernetes.io/managed-by: management-api
spec:
  name: "JPMM"
  subdomain: "jpmm.jpm.com"
  gatewayType: kong
  replicas: 1
  nodes:
    - name: "fleet-jpmm-kong-1"
      index: 1
      gatewayType: "kong"
      datacenter: "us-east-2"
      region: "us-east-2"
      status: "running"
